name: CI-Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:   
        - uses: actions/checkout@v2
          with:
            repository: heremaps/movetk
            submodules: recursive
            path: movetk
        - name: install dependencies
          run: |
              sudo apt-get update
              sudo apt-get install libboost-all-dev cmake libcgal-dev doxygen gcc g++ 
              sudo apt-get install libgdal-dev libgsl-dev libgslcblas0 gsl-bin libgsl23 make libmpfr-dev git 
        - name: install Geographiclib
          run: |
               wget https://sourceforge.net/projects/geographiclib/files/distrib/GeographicLib-1.50.1.zip/download 
               mv download GeographicLib-1.50.1.zip 
               unzip GeographicLib-1.50.1.zip 
               cd GeographicLib-1.50.1 
               mkdir BUILD
               cd BUILD 
               cmake .. && make && make test && sudo make install
        - name: build movetk
          run: |
              export LIBRARY_PATH=/usr/local/lib/ 
              echo $LIBRARY_PATH 
              cd movetk
              ./ci.sh
        - uses: actions/checkout@v2
          with:
            path: movetk-app-template
        - name: build this app
          run: |
              cd movetk-app-template
              ./ci.sh
        - name: Get GeoLife trajectories
          run: |
              cd movetk-app-template
              wget https://download.microsoft.com/download/F/4/8/F4894AA5-FDBC-481E-9285-D5F8C4C4F039/Geolife%20Trajectories%201.3.zip
              unzip Geolife\ Trajectories\ 1.3.zip
        - name: Preprocess  GeoLife trajectories
          run: |
            cd movetk-app-template
            python3 geolife.py
            cd out
            mv out.csv trajectories.csv
        - name: Get trajectory statisics
          run: |
              cd movetk-app-template/out
              ../Release/src/process_trajectories trajectories.csv
              pwd
              ls -lrt
        - uses: actions/upload-artifact@v2
          with:
              name: trajectories.csv
              path: /home/runner/work/movetk-app-template/movetk-app-template/movetk-app-template/out/trajectories.csv
        - uses: actions/upload-artifact@v2
          with:
              name: trajectory_statistics.csv
              path: /home/runner/work/movetk-app-template/movetk-app-template/movetk-app-template/out/trajectory_statistics.csv
        - uses: actions/upload-artifact@v2
          with:
              name: output_trajectories.geojson
              path: /home/runner/work/movetk-app-template/movetk-app-template/movetk-app-template/out/output_trajectories.geojson
